### ISSUE TITLE
[Bug] Not compatible with storybook 7

### ISSUE THREAD

**Issue by PascalvdHoek** [storybookjs/addon-styling#22]
### Describe the bug

Im trying to install this add on with storybook 7, but getting npm conflicts. 
It keeps asking for versions 6.5.8, but im at 7.0.0-rc.8

### Steps to reproduce the behavior

1. add storybook at 7.0.0-rc.8
2. add storybook styling
3. See error

### Expected behavior

Hopefully make it compatible with 7.0.0-rc8

### Screenshots and/or logs

If applicable, add screenshots and/or logs to help explain your problem.

### Additional context

some example errors:
<img width="702" alt="image" src="https://user-images.githubusercontent.com/56636556/230186450-e69d3633-409d-4f86-8f4f-20fb1a9ab0ec.png">
<img width="774" alt="image" src="https://user-images.githubusercontent.com/56636556/230186498-29b1c5a1-ce54-47cb-9678-5a476cbef726.png">

**Comment by Integrayshaun** [comment]
Hey @PascalvdHoek

I'm just working out a few details to release v1.0.0 which will be compatible with SB 7 🎉 

you can use it now by running:
`npm install -D @storybook/addon-styling@next`

**Comment by PascalvdHoek** [comment]
Great it works with hte @next and a downgrade to sass-loader@10.4.1

**Comment by abdouthetif** [comment]
I have the same problem but i can't downgrade to sass-loader@10.4.1 because i'm using @symfony/webpack-encore@4.2.0 which needs sass-loader@^13.0.0

**Comment by sklawren** [comment]
I am using 1.0.0-next.1 and Storybook with Webpack 5 and get the following error when I set `cssModules: true` as [per the docs](https://github.com/storybookjs/addon-styling/blob/next/docs/api.md#optionscssmodules).
```bash
ValidationError: Invalid options object. CSS Loader has been initialized using an options object that does not match the API schema.
 - options.modules should be one of these:
   boolean | "local" | "global" | "pure" | "icss" | object { auto?, mode?, localIdentName?, localIdentContext?, localIdentHashSalt?, localIdentHashFunction?, localIdentHashDigest?, localIdentHashDigestLength?, hashStrategy?, localIdentRegExp?, getLocalIdent?, namedExport?, exportGlobals?, exportLocalsConvention?, exportOnlyLocals? }
   -> Allows to enable/disable CSS Modules or ICSS and setup configuration.
   -> Read more at https://github.com/webpack-contrib/css-loader#modules
   Details:
    * options.modules should be a boolean.
    * options.modules should be one of these:
      "local" | "global" | "pure" | "icss"
    * options.modules should be an object:
      object { auto?, mode?, localIdentName?, localIdentContext?, localIdentHashSalt?, localIdentHashFunction?, localIdentHashDigest?, localIdentHashDigestLength?, hashStrategy?, localIdentRegExp?, getLocalIdent?, namedExport?, exportGlobals?, exportLocalsConvention?, exportOnlyLocals? }
    at validate (/Users/me/project/node_modules/schema-utils/dist/validate.js:105:11)
    at Object.getOptions (/Users/me/project/node_modules/webpack/lib/NormalModule.js:588:18)
    at Object.loader (/Users/me/project/node_modules/css-loader/dist/index.js:22:27)
```

This error does not happen with Storybook built with Vite. Only Webpack.

**Comment by stevensacks** [comment]
I am using 1.0.0-next.1 and Storybook with Webpack 5 and get the following error when I set `cssModules: true` as [per the docs](https://github.com/storybookjs/addon-styling/blob/next/docs/api.md#optionscssmodules).
```bash
ValidationError: Invalid options object. CSS Loader has been initialized using an options object that does not match the API schema.
 - options.modules should be one of these:
   boolean | "local" | "global" | "pure" | "icss" | object { auto?, mode?, localIdentName?, localIdentContext?, localIdentHashSalt?, localIdentHashFunction?, localIdentHashDigest?, localIdentHashDigestLength?, hashStrategy?, localIdentRegExp?, getLocalIdent?, namedExport?, exportGlobals?, exportLocalsConvention?, exportOnlyLocals? }
   -> Allows to enable/disable CSS Modules or ICSS and setup configuration.
   -> Read more at https://github.com/webpack-contrib/css-loader#modules
   Details:
    * options.modules should be a boolean.
    * options.modules should be one of these:
      "local" | "global" | "pure" | "icss"
    * options.modules should be an object:
      object { auto?, mode?, localIdentName?, localIdentContext?, localIdentHashSalt?, localIdentHashFunction?, localIdentHashDigest?, localIdentHashDigestLength?, hashStrategy?, localIdentRegExp?, getLocalIdent?, namedExport?, exportGlobals?, exportLocalsConvention?, exportOnlyLocals? }
    at validate (/Users/me/project/node_modules/schema-utils/dist/validate.js:105:11)
    at Object.getOptions (/Users/me/project/node_modules/webpack/lib/NormalModule.js:588:18)
    at Object.loader (/Users/me/project/node_modules/css-loader/dist/index.js:22:27)
```

This error does not happen with Storybook built with Vite. Only Webpack.

**Comment by Integrayshaun** [comment]
`@storybook/addon-styling@1.0.0` has been released which is upgrade for Storybook 7 🎉 

@stevensacks your issue has been fixed for v1.0.0 😁

**Comment by stevensacks** [comment]
@Integrayshaun I updated to 1.0.0, but still getting this error. I tried clearing my storybook cache, deleting node_modules, package-lock.json and npm install again.

```bash
ValidationError: Invalid options object. CSS Loader has been initialized using an options object that does not match the API schema.
node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[7].use[1]!./src/components/Button/styles.module.css undefined
 - options.modules should be one of these:
   boolean | "local" | "global" | "pure" | "icss" | object { auto?, mode?, localIdentName?, localIdentContext?, localIdentHashSalt?, localIdentHashFunction?, localIdentHashDigest?, localIdentHashDigestLength?, hashStrategy?, localIdentRegExp?, getLocalIdent?, namedExport?, exportGlobals?, exportLocalsConvention?, exportOnlyLocals? }
   -> Allows to enable/disable CSS Modules or ICSS and setup configuration.
   -> Read more at https://github.com/webpack-contrib/css-loader#modules
   Details:
    * options.modules should be a boolean.
    * options.modules should be one of these:
      "local" | "global" | "pure" | "icss"
    * options.modules should be an object:
      object { auto?, mode?, localIdentName?, localIdentContext?, localIdentHashSalt?, localIdentHashFunction?, localIdentHashDigest?, localIdentHashDigestLength?, hashStrategy?, localIdentRegExp?, getLocalIdent?, namedExport?, exportGlobals?, exportLocalsConvention?, exportOnlyLocals? }
```
Here's my relevant `main.ts` configuration:
```ts
import type {StorybookConfig} from '@storybook/react-webpack5';
import postcss from 'postcss';

const config: StorybookConfig = {
    addons: [
        {
            name: '@storybook/addon-styling',
            options: {
                cssModules: true,
                postcssLoaderOptions: {
                    implementation: postcss,
                },
            },
        },
        '@storybook/addon-links',
        '@storybook/addon-essentials',
        'storybook-react-i18next',
        'storybook-addon-designs',
    ],
    // ...
};
```

In Storybook 6, I was using https://github.com/onwidget/storybook-css-modules and @storybook/addon-postcss.

**Comment by Integrayshaun** [comment]
I have no idea what happened but when 1.0.0 was published it didn't have the css-loader changes to make modules work 💀 

I've just published `1.0.1` that includes the fix
